theme: jekyll-theme-tactile
title: SVG Community Group
description: "A group to gather and incubate new features and requirements for SVG — making it easier for software developers and content creators in the SVG community to engage with the SVG standardization process."
show_downloads: false
